#!/bin/bash
#chmod u+x ~/scripts/flask_new.sh
#create a new github repo named mynewproject prior to running this script


#This script creates a new flask project named <project>
#from ~/projects/boilerplates/flasktemplate boilerplate
#installs required packages and checks in the initial commit of the project

cp -r ~/projects/boilerplates/flasktemplate ~/projects/flask/testproject
cd ~/projects/flask/testproject
#flask_home=~/projects/boilerplates
#cd $flask_home
#git clone git@github.com:aregsar/flasktemplate.git
#cp -r flasktemplate mynewproject
#cd mynewproject
chmod -R 755 .git
rm -rf .git
virtualenv -p $(which python) venv
. venv/bin/activate
pip install -r requirements.txt
deactivate
git init
git remote add origin git@github.com:aregsar/testproject.git
git add -A
git commit -m "initial commit"
git push -u origin --all

